### ISSUE TITLE
I don't see map at all

### ISSUE THREAD

**Issue by dzarezenko** [schlunsen/nuxt-leaflet#10]
I have installed `npm` package, added module to the nuxt config file and added map to my `index.vue` page but don't see a map at all. What is wrong?

**Comment by schlunsen** [comment]
Npm has been updated

**Comment by dzarezenko** [comment]
The problem actually was connected with `style="height: 100%"` attribute of the main `<div>`. I have changed on `style="height: 1000px"` and map were appeared.
