### ISSUE TITLE
Update l-icon-default component to l-icon, to enable HTML icons

### ISSUE THREAD

**Issue by blackspike** [schlunsen/nuxt-leaflet#11]
It would be great to update or add the [i-icon](https://korigan.github.io/Vue2Leaflet/#/components/l-icon/) component  to enable HTML icons. I would prefer to show place names with custom HTML/CSS than an image.

It looks like the l-icon-default will be [deprecated next version](https://korigan.github.io/Vue2Leaflet/#/components/l-icon-default/) too. Many thanks for this excellent Nuxt plugin!

**Comment by schlunsen** [comment]
Feel free to make a pull request :)

**Comment by blackspike** [comment]
Challenge accepted! Although it's not working in Vue2Leaflet either ...I'll take a look!
