### ISSUE TITLE
[Question] Disable scroll zoom functionality

### ISSUE THREAD

**Issue by Extarys** [schlunsen/nuxt-leaflet#13]
thanks for this lil' module.

I'm trying to figure out how I can disable zoom feature with the scroll wheel, like embedded Google Maps. Pressing CTRL to zoom would be nice.

How can I access the map object to use javascript with it inside a component?

:cheese:

**Comment by schlunsen** [comment]
See https://github.com/schlunsen/nuxt-leaflet/issues/8
