### ISSUE TITLE
Add custom vue leaflet component

### ISSUE THREAD

**Issue by riso348** [schlunsen/nuxt-leaflet#14]
Hi,
is it possible to add custom leaflet component or remove unnecessary components?
For example i want add https://github.com/jperelli/vue2-leaflet-markercluster
and not use some included in https://github.com/schlunsen/nuxt-leaflet/blob/master/lib/templates/plugin.js that i dont use. Or should i create my own plugin. 
Thank you

**Comment by pablocattaneo** [comment]
Hi @riso348 !
Do you find a solution for your issue? I am in similar situation.

**Comment by riso348** [comment]
Yes, i create my own plugin according to nuxt-leaflet, it looks like this:
(Typescript style)
https://jsbin.com/bofowayewa/edit?html,js,console

And include it in nuxt.config.ts:
{src: "~/plugins/modules/leaflet", ssr: false}

**Comment by pablocattaneo** [comment]
Thanks you so much @riso348 !!

Very handful!! you made my day.

Regards!

**Comment by pablocattaneo** [comment]
@riso348 I clean the code, my final version look like this:

```javascript
import Vue from "vue";
import * as L from "leaflet";
import Vue2LeafletMarkerCluster from "vue2-leaflet-markercluster";
Vue.component("v-marker-cluster", Vue2LeafletMarkerCluster);

const LeafletPlugin = {
  install(Vue) {
    // Expose Leaflet
    Vue.prototype.$L = L;
  }
};

Vue.use(LeafletPlugin);
```
