### ISSUE TITLE
How to use geoman.io with nuxt-leaflet ?

### ISSUE THREAD

**Issue by vodniciarv** [schlunsen/nuxt-leaflet#21]
How to use the [leaflet.pm](https://github.com/codeofsumit/leaflet.pm) project with nuxt-leaflet?

**Comment by vodniciarv** [comment]
On QA:

- [StackOverflow](https://stackoverflow.com/questions/55938154/how-to-use-geoman-io-with-nuxt-leaflet)
- [RUStackOverflow](https://ru.stackoverflow.com/questions/976966/%D0%9A%D0%B0%D0%BA-%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%D1%82%D1%8C-geoman-io-%D0%BA-nuxt-leaflet)
- [Toster](https://toster.ru/q/627391)

**Comment by schlunsen** [comment]
I regard this as spam
