### ISSUE TITLE
Options? What are they?

### ISSUE THREAD

**Issue by movepixels** [schlunsen/nuxt-leaflet#39]
Just wondering what
```
['nuxt-leaflet', { /* module options */ }],
```
What are the available options? 
Are they specific to this module / leaflet module / Vue2Leaflet component.

If you could provide a list of what these options are that are available and from where to reference from would be great.

Thanks

**Comment by schlunsen** [comment]
I don't think they are used yet.

An idea was to have an options for which types of Vue2Leaflet you would want to include.

Take a look at https://github.com/schlunsen/nuxt-leaflet/blob/master/lib/module.js

Pull requests are welcome!

Thanks
