### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ScreamZ** [schlunsen/nuxt-leaflet#4]
Hello,

I'm getting : `Module build failed: ValidationError: PostCSS Loader Invalid Options`

Any idea ?

Regards

PS : Example is outdated `v-map` is now `l-map`

**Comment by schlunsen** [comment]
No idea to be honest, but check your modules versions.

Please report to this issue thread if you find the solution.

Thanks for the heads up on the example - it's corrected now.

**Comment by ScreamZ** [comment]
Hey,

after some reading I figured out that it seems related to a specific `postcss-loader` version.

People are talking about `"postcss-loader": "^2.1.2"`,  they might have patched in 2.1.3.

I set it to `"postcss-loader": "^2.1.1"` and the error disappeared, we could watch this for the future.
