### ISSUE TITLE
how to apply different map styles

### ISSUE THREAD

**Issue by jensgeffken** [schlunsen/nuxt-leaflet#47]
i would like to change the map layout (color etc) on overall layout changes, i did found this resource:
[https://leaflet-extras.github.io/leaflet-providers/preview/](url)
but i have no idea how to implement it with nuxt-leaflet. 
Help is appreciated. Thanks

**Comment by schlunsen** [comment]
I would think you could do so by changing
```
  <l-tile-layer url="http://{s}.tile.osm.org/{z}/{x}/{y}.png"></l-tile-layer>
```
