### ISSUE TITLE
Adding plugin to nuxt-leaflet

### ISSUE THREAD

**Issue by sowinski** [schlunsen/nuxt-leaflet#48]
Hi,

how can I add a plugin to nuxt-leaflet?

Currently I would like to add a heatmap. I found a lot of plugins in the leaflet page. But I do not know how to add them.

I would like to try this one, but I don't know how to add this?
https://www.patrick-wied.at/static/heatmapjs/example-heatmap-leaflet.html

**Comment by schlunsen** [comment]
Hi, 

Please checkout https://github.com/vue-leaflet/Vue2Leaflet which this library is a wrapper around

**Comment by schlunsen** [comment]
Also see https://github.com/schlunsen/nuxt-leaflet/issues/14
