### ISSUE TITLE
Rendering map is too slow

### ISSUE THREAD

**Issue by claide** [schlunsen/nuxt-leaflet#49]
Hi, thanks for this module for leaflet.
I tried to loop all markers from some API using `v-for` but map rendered so slow specially when there's too many markers.

```
<l-marker
    v-for="c in cases"
    :icon="icon"
    :key="c.case_no"
    :lat-lng="[c.latitude,c.longitude]"
>
```

```
Axios.get(`https://some-api/cases`).then(
    response => {
      this.cases = response.data.filter(item => item.latitude != 'TBA')
      this.isLoading = false
    }
)
```

**Comment by schlunsen** [comment]
Hi claide, thank you for reporting this.

This library is a wrapper for making it easy to integrate with nuxt. It's using https://github.com/vue-leaflet/Vue2Leaflet which again is a wrapper for https://github.com/Leaflet/Leaflet.

When you find a solution, i'm sure a pull request to the appropriate library will be greatly appreciated.
