### ISSUE TITLE
Vuetify v-navigation-drawer goes under the map

### ISSUE THREAD

**Issue by lucasflorent** [schlunsen/nuxt-leaflet#50]
Hello everyone,
I'm new with NuxtJs and I try to use Nuxt-Leaflet with Vuetify.
I used [the example](https://github.com/schlunsen/nuxt-leaflet/tree/master/example/nuxt-leaflet-example) of the masterbranch but I have a problem with the navigation drawer in Firefox as in Chrome:

1- the navigation drawer goes under the leaflet map when I click on it.

2- the navigation drawer goes on the v-app-bar even when I put the v-navigation-drawer clipped property on True.

Does anyone know how to fix it?
Thank you very much in advance,

Florent LUCAS

![copieEcran_Nuxt-Leaflet_Bug](https://user-images.githubusercontent.com/50375095/78774936-b3b08700-7995-11ea-8fc4-8307d389a61d.png)

**Comment by schlunsen** [comment]
Hi  @lucasflorent,

This issue tracker is for issues regarding the library not general help. Please seek out the appropriate forums for answer to your question. Css z-index is what you want to look for.

Thank you.

**Comment by lucasflorent** [comment]
Hello @schlunsen,

Thanks for your answer.
I agree I why asking for help but I think these two problems are also (very) minor issues in the library. That's why I posted here and not in a forum.
However, I will looking for changing the z-index in the <v-content>.
Thanks again!

Florent
