### ISSUE TITLE
How use latLngBounds in Nuxt?

### ISSUE THREAD

**Issue by io777** [schlunsen/nuxt-leaflet#52]
How use latLngBounds in Nuxt? If  `import { latLngBounds } from "leaflet"; ` in component. This good work in vue2, but not work in Nuxt. I have error on page - ReferenceError window is not defined. This is related to the server-side-rendered.

**Comment by timwis** [comment]
Hey @io777 I've got the same issue. Did you find a solution for it?

**Comment by io777** [comment]
Hello!  I use [nuxt-leaflet](https://www.npmjs.com/package/nuxt-leaflet) (npm i nuxt-leaflet)
`<client-only>
          <l-map style="height: 989px;width: 989px;"
                 :zoom="zoom"
                 :min-zoom="minZoom"
                 :max-zoom="maxZoom"
                 :center="center"
                 :max-bounds="maxBounds"
                 @update:zoom="zoomUpdated"
          >
              <l-tile-layer :url="url" :tile-size="tileSize" :no-wrap="true" :attribution="attribution"></l-tile-layer>
          </l-map>
        </client-only>`

`<script>
    export default {
        name: "Map",
        data () {
            return {
              url: 'https://pubg.game-data.ru/maps-api/erangel/{z}/{y}x{x}.png',
              map: 'erangel',
              zoom: 3,
              center: [68, -91],
              minZoom: 3,
              maxZoom: 7,
              tileSize: 100,
              maxBounds: [
                [68, -91],
                [68, -91]
              ],
              attribution: '',
            };
        },
        methods: {
            zoomUpdated (zoom) {
                this.zoom = zoom;
              if(zoom === 3) {
                this.maxBounds = [
                    [68, -91],
                    [68, -91]
                  ];
              }
              if(zoom === 4) {
                this.maxBounds = [
                    [4.3, -4.3],
                    [95, -180]
                  ];
              }
              if(zoom === 5) {
                this.maxBounds = [
                    [4.3, -4.3],
                    [95, -180]
                  ];
              }
              if(zoom === 6) {
                this.maxBounds = [
                    [4.3, -4.3],
                    [95, -180]
                  ];
              }
              if(zoom === 7) {
                this.maxBounds = [
                    [5.35, -5.35],
                    [95, -180]
                  ];
              }
            },
            mapSelect (map) {
                this.map = map;
                this.url = https://pubg.game-data.ru/maps-api/${map}/{z}/{y}x{x}.png;
            }
          }
    }
</script>`

**Comment by timwis** [comment]
Ah, okay, so you didn't end up needing `latLngBounds`?

**Comment by io777** [comment]
Sorry, it was a long time ago. I remembered, I wanted to use markers and asked this one, in the end I did not find an answer.
