### ISSUE TITLE
Bump the version dependency of vue2-leaflet

### ISSUE THREAD

**Issue by ajmas** [schlunsen/nuxt-leaflet#62]
Could you change the dependency version of vue2-leaflet to be the latest? Currently it is 2.6.0 - thanks

**Comment by ManUtopiK** [comment]
I just installed the version with `npm install vue2-leaflet@last` and everything seems to work as usual.
Better, that's removed a strange error message `Uncaught TypeError: Cannot read property '_leaflet_pos' of undefined`

Bump the version should be safe!

**Comment by schlunsen** [comment]
Version bumped
