### ISSUE TITLE
Can we have an example please?

### ISSUE THREAD

**Issue by RonAlmog** [schlunsen/nuxt-leaflet#71]
in the main page, there is an example for static map, using params for location.
can we get an example please, for dynamically creating a map? with center, zooming option, several markers.
If possible, please share some example of how to use that this.$L methods. How to connect them to a specific map (assuming more than one).  Again, for example, please show a simple button on the page that takes you to another location. Thanks!

**Comment by schlunsen** [comment]
Will be happy to merge a good pull request

**Comment by RonAlmog** [comment]
;( not exactly the answer I was hoping for, but I understand.
